name: cocoahttp
version: 0.0.1
description: >-
  A super simple example of calling C code from Dart with FFI
# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.7.0
  ffi: ">=1.1.2<2.0.0"
