name: cupertinohttp
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.18.0-edge.e82d6d1a4f4fbf6a425ac9a4ad449f0304344f75 <3.0.0'

dependencies:
  args: ^2.1.0

  native_library:
    path: ../native_library

dev_dependencies:
  logging: ^1.0.2
  lints: ^2.0.0
  test: ^1.16.0
