name: ffitest

environment:
  sdk: '>=2.16.0 <3.0.0'

ffigen:
  language: 'objc'
  output: 'nsurlsession_bindings.dart'
  headers:
    entry-points:
      - '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSURLSession.h'

dependencies:
  ffi: ^1.1.2
  native_library:
    path: ../native_library

dev_dependencies: 
  ffigen:
    path: ../../ffigen

